name: Create a Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false

env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Git Identity
        run: |
          git config --global user.name 'SnO2WMaN'
          git config --global user.email 'SnO2WMaN@users.noreply.github.com'
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile

      - name: Manually version up
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }}
      - name: Automatically selected version by conventional commits
        if: ${{ !github.event.inputs.version }}
        run: npm version $($(yarn bin conventional-recommended-bump) -p conventionalcommits)

      - id: package-version
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "::set-output name=version::${version}"

      - id: pull-request-info
        run: |
          echo "::set-output name=branch::releases/v${{ steps.package-version.outputs.version }}"
          echo "::set-output name=title::$(git log -1 --pretty=%s)"
          echo "::set-output name=body::$(eval $(yarn bin conventional-changelog))"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.pull-request-info.outputs.branch }}
          title: ${{ steps.pull-request-info.outputs.title }}
          body: ${{ steps.pull-request-info.outputs.body }}
          delete-branch: true
          labels: |
            release
