name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - master

env:
  CI: true

jobs:
  publish-github-packages:
    name: Publish to GitHub Packages
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
