name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false

env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Git Identity
        run: |
          git config --global user.name 'SnO2WMaN'
          git config --global user.email 'SnO2WMaN@users.noreply.github.com'
      - run: yarn install --frozen-lockfile

      - name: Manually version up
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }}

      - name: Automatically selected version by conventional commits
        if: ${{ !github.event.inputs.version }}
        run: npm version $($(yarn bin conventional-recommended-bump) -p conventionalcommits)

      - name: Get current package version
        id: current-version
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "::set-output name=version::${version}"

      - id: conventional-changelog
        run: echo "::set-output name=body::$(yarn bin conventional-changelog)"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ success() }}
        with:
          tag_name: '${{ github.ref }}'
          release_name: 'v${{ github.ref }}'
          body: '${{ steps.conventional-changelog.outputs.body }}'
          draft: false
