name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false

env:
  CI: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Git Identity
        run: |
          git config --global user.name 'SnO2WMaN'
          git config --global user.email 'SnO2WMaN@users.noreply.github.com'
      - run: yarn install --frozen-lockfile

      - name: Manually version up
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }}

      - name: Automatically selected version by conventional commits
        if: ${{ !github.event.inputs.version }}
        run: npm version $($(yarn bin conventional-recommended-bump) -p conventionalcommits)

  release:
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Git Identity
        run: |
          git config --global user.name 'SnO2WMaN'
          git config --global user.email 'SnO2WMaN@users.noreply.github.com'
      - run: yarn install --frozen-lockfile

      - name: Get current package version
        id: current-version
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "::set-output name=version::${version}"

      - id: conventional-changelog
        run: |
          echo "::set-output name=body::$(yarn bin conventional-changelog)"

      - id: npm-pack
        run: |
          echo "::set-output name=tarball::$(npm pack)"

      - uses: actions/create-release@v1
        id: create-release
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: ${{ steps.conventional-changelog.outputs.body }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.npm-pack.outputs.tarball }}
          asset_name: ${{ steps.npm-pack.outputs.tarball }}
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
